;;; tetris-60-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tetris-60.el

(autoload 'tetris-60 "tetris-60" "\
Play the Tetris-60 game." t)
(register-definition-prefixes "tetris-60" '("tetris-60-"))

;;; End of scraped data

(provide 'tetris-60-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tetris-60-autoloads.el ends here
