# ~/.config/hyprlock/hyprlock.conf
general {
    disable_loading_bar = true
    hide_cursor = false
    grace = 0
    no_fade_in = true
}

background {
    monitor =
    path = /home/veter/Pic/Asitaka.jpg
    blur_passes = 0
    blur_size = 0
    noise = 0.01
    contrast = 1.0
    brightness = 1.0
    vibrancy = 0.0
}

input-field {
    monitor =
    size = 350, 50           # +50%
    outline_thickness = 3    # +50%
    dots_size = 0.3          # +50%
    dots_spacing = 0.3       # +50%
    dots_center = true
    outer_color = rgb(255, 0, 255)
    inner_color = rgb(60, 60, 60)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = <i>Пароль...</i>
    hide_input = false
    position = 0, 50
    halign = center
    valign = center
}

# Рамка для времени
time-field {
    monitor =
    size = 300, 60
    outline_thickness = 3
    outer_color = rgb(75, 0, 130)
    inner_color = rgb(40, 40, 40)
    font_color = rgb(255, 255, 255)
    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = Veter
    color = rgb(255, 0, 255)
    font_size = 27           # +50% (18 → 27)
    font_family = Comic Mono
    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M:%S')"
    color = rgb(255, 255, 255)
    font_size = 24           # +50% (16 → 24)
    font_family = Comic Mono
    position = 0, -50
    halign = center
    valign = center
}
