# ==========================================
# Главный конфиг Mango
# ==========================================

# Подключаем все файлы конфигурации
source = ~/.config/mango/bindings.conf
source = ~/.config/mango/tag.conf
source = ~/.config/mango/env.conf
source = ~/.config/mango/appearance.conf
source = ~/.config/mango/animations.conf
source = ~/.config/mango/layouts.conf
source = ~/.config/mango/rules.conf
source = ~/.config/mango/startup.conf
source = ~/.config/mango/monitors.conf

# Эти файлы могут отсутствовать, ошибки не будет
#source-optional = ~/.config/mango/scratchpad.conf
