# ==========================================
# Автозапуск программ (Startup)
# ==========================================

# Запускаем вашу оболочку
exec-once = qs -c noctalia-shell
#exec-once = fcitx5 -d &
# Если хотите вернуть waybar, раскомментируйте строку ниже
# exec-once = waybar

# Другие полезные программы
# exec-once = mako
# exec-once = nm-applet
